# Generated by Django 4.1.7 on 2023-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.FloatField(null=True),
        ),
    ]
