# Generated by Django 4.1.7 on 2023-04-28 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='login',
            new_name='worker',
        ),
        migrations.AddField(
            model_name='payment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshopApp.schedule'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='card_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='workshopApp.appointment'),
            preserve_default=False,
        ),
    ]
