# Generated by Django 4.1.7 on 2023-04-28 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApp', '0002_rename_login_schedule_worker_payment_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshopApp.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
