# Generated by Django 4.1.7 on 2023-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApp', '0002_alter_login_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='card_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
