# Generated by Django 4.1.7 on 2023-04-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshopApp', '0005_alter_payment_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshopApp.payment'),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
